# Generated by Django 5.2.8 on 2025-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_phone', models.CharField(max_length=20)),
                ('ct_guests', models.IntegerField()),
                ('ct_date', models.DateField()),
                ('ct_time', models.TextField()),
                ('ct_request', models.TextField(blank=True)),
            ],
        ),
    ]
